### ISSUE TITLE
db relations

### ISSUE THREAD

**Issue by agga1** [maciektr/IntroductionToDatabases#2]
-no link between conferenceDayReservation and workshopReservation? how to pay for workshop res?
-conference location, start-end day, nr of seats available?

**Comment by agga1** [comment]
-add on delete cascade? in 
      Workshop_registration references reservation_id
     Conference-day_registration references reservation_id
(to avoid writing triggers :D )

**Comment by maciektr** [comment]
- There is still connection via Conference_day_reservations -> Conference_days -> Workshops -> Workshop_reservation. Storing the connection in database as foreing key would be redundant.

- Location as varchar? We can do that if you wish. You just need to change the vertabelo scheme. 
Agree, that Conference_days lacks number_of_seats. 

- Sure :)
